{{- $globsecrets := .Files.Glob "secrets/*.yaml" -}}

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-secret
type: Opaque
stringData:
  {{ if $globsecrets }}
  {{ ($globsecrets).AsSecrets | indent 0 }}
  {{ end }}
  POSTGRES_PASSWORD: {{ default "NONE" .Values.BACKEND.STATEFUL.POSTGRES.SECRETS.PASSWORD }}
  POSTGRES_DB: {{ default "NONE" .Values.BACKEND.STATEFUL.POSTGRES.SECRETS.DB }}
  POSTGRES_USER: {{ default "NONE" .Values.BACKEND.STATEFUL.POSTGRES.SECRETS.USER }}
  RABBITMQ_DEFAULT_USER: {{ default "NONE" .Values.BACKEND.STATELESS.RABBITMQ.SECRETS.DEFAULT.USER }}
  RABBITMQ_DEFAULT_PASS: {{ default "NONE" .Values.BACKEND.STATELESS.RABBITMQ.SECRETS.DEFAULT.PASS }}
  RABBITMQ_DEFAULT_URL: {{ default "NONE" .Values.BACKEND.STATELESS.RABBITMQ.SECRETS.DEFAULT.URL }}
