apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ template "todo-app.namespace" . }}
  name: todo-storage-ingestion
  labels:
    todo-app-deployment: todo-storage-ingestion
spec:
  replicas: {{ .Values.BACKEND.STATELESS.STORAGE.INGESTION.REPLICAS }}
  selector:
      matchLabels:
        todo-app-pod: todo-storage-ingestion
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        todo-app-pod: todo-storage-ingestion
    spec:
      restartPolicy: Always
      initContainers:
      - name: init-rabbitmq
        image: busybox
        command: ['sh', '-c', 'until nslookup todo-rabbitmq; do echo waiting for RabbitMQ; sleep 2; done;']
      containers:
      - name: todo-storage-ingestion
        image: {{ .Values.VARS.DOCKER.HUB.ID }}/todo-storage-ingestion:{{ .Values.BACKEND.STATELESS.STORAGE.INGESTION.IMAGE.TAG }}
        imagePullPolicy: {{ .Values.BACKEND.STATELESS.STORAGE.INGESTION.IMAGE.PULLPOLICY }}
        envFrom:
          - configMapRef:
              name: todo-config
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: todo-secret
              key: POSTGRES_PASSWORD
        resources:
          limits:
            memory: "{{ .Values.BACKEND.STATELESS.STORAGE.INGESTION.MEMORY }}"
